---
jobs:
- name: build-pcfops-image
  public: true
  serial: true
  plan:
  - get: pcfops-docker-release
    trigger: true
    params:
      include_source_tarball: true
  - task: extract
    config:
      platform: linux
      inputs:
      - name: pcfops-docker-release
      outputs:
      - name: source
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: tar
        args:
          - --extract
          - --gzip
          - --strip-components=1
          - --directory=source
          - --file=pcfops-docker-release/source.tar.gz
  - put: pcfops-image
    params:
      build: source
      tag: pcfops-docker-release/version

resources:
- name: pcfops-docker-release
  type: github-release
  source:
    owner: EngineerBetter
    repository: pcfops-docker
    access_token: {{github_access_token}} # Avoids rate limits
- name: pcfops-image
  type: docker-image
  source:
    username: {{dockerhub_user}}
    password: {{dockerhub_password}}
    repository: engineerbetter/pcf-ops
