---
jobs:
- name: get-terraform
  public: true
  serial: true
  plan:
  - get: terraform-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: terraform-github-release
      outputs:
      - name: terraform
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          version=$(cat terraform-github-release/version)
          url="https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_amd64.zip"
          wget --output terraform.zip "$url"
          unzip -d terraform terraform.zip
  - put: terraform-s3-release
    params: {file: terraform/terraform}

- name: get-cf-cli
  public: true
  serial: true
  plan:
  - get: cf-cli-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: cf-cli-github-release
      outputs:
      - name: cf
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          version=$(cat cf-cli-github-release/version)
          url="https://cli.run.pivotal.io/stable?release=linux64-binary&version=${version}&source=github-rel"
          wget --output cli.tgz "$url"
          tar -C cf -xzf cli.tgz
  - put: cf-cli-s3-release
    params: {file: cf/cf}

- name: get-bosh-cli
  public: true
  serial: true
  plan:
  - get: bosh-cli-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: bosh-cli-github-release
      outputs:
      - name: bosh-cli
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          version=$(cat bosh-cli-github-release/version)
          url="https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-${version}-linux-amd64"
          wget --output bosh-cli/bosh "$url"
  - put: bosh-cli-s3-release
    params: {file: bosh-cli/bosh}

- name: build-pcfops-image
  public: true
  serial: true
  plan:
  - get: pcfops-docker-tag
    params: {bump: minor}
  # Download Dockerfile
  - get: pcfops-github
    trigger: true
  # Download dependancies
  - get: terraform-s3-release
    trigger: true
    passed: [get-terraform]
  - get: cf-cli-s3-release
    trigger: true
    passed: [get-cf-cli]
  - get: jq-github-release
    trigger: true
    params:
      globs: [jq-linux64]
  - get: om-github-release
    trigger: true
    params:
      globs: [om-linux]
  - get: fly-github-release
    trigger: true
    params:
      globs: [fly_linux_amd64]
  - get: bosh-cli-s3-release
    trigger: true
    passed: [get-bosh-cli]
  # Copy dependancies
  - task: copy
    config:
      platform: linux
      inputs:
      - name: pcfops-github
      - name: terraform-s3-release
      - name: cf-cli-s3-release
      - name: jq-github-release
      - name: om-github-release
      - name: fly-github-release
      - name: bosh-cli-s3-release
      outputs:
      - name: builddir
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
          - -c
          - |
            cp pcfops-github/Dockerfile builddir/Dockerfile
            cp terraform-s3-release/terraform builddir/terraform
            cp cf-cli-s3-release/cf builddir/cf
            cp jq-github-release/jq-linux64 builddir/jq
            cp om-github-release/om-linux builddir/om
            cp fly-github-release/fly_linux_amd64 builddir/fly
            cp bosh-s3-release/bosh builddir/bosh
  - put: pcfops-image
    params:
      build: builddir
      tag: pcfops-docker-tag/version
      tag_as_latest: true
  - put: pcfops-docker-tag
    params: {file: pcfops-docker-tag/version}

resources:
- name: pcfops-docker-tag
  type: semver
  source:
    driver: s3
    key: docker-tag
    bucket: pcf-docker-pipeline
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: eu-west-1

- name: pcfops-github
  type: git
  source:
    uri: https://github.com/EngineerBetter/pcfops-docker.git
- name: pcfops-image
  type: docker-image
  source:
    username: {{dockerhub_user}}
    password: {{dockerhub_password}}
    repository: engineerbetter/pcf-ops

- name: terraform-github-release
  type: github-release
  source:
    owner: hashicorp
    repository: terraform
    access_token: {{github_access_token}} # Avoids rate limits
- name: terraform-s3-release
  type: s3
  source:
    versioned_file: terraform/terraform
    bucket: pcf-docker-pipeline
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: eu-west-1

- name: cf-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cli
    access_token: {{github_access_token}} # Avoids rate limits
- name: cf-cli-s3-release
  type: s3
  source:
    versioned_file: cf/cf
    bucket: pcf-docker-pipeline
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: eu-west-1

- name: jq-github-release
  type: github-release
  source:
    owner: stedolan
    repository: jq
    access_token: {{github_access_token}} # Avoids rate limits

- name: om-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: {{github_access_token}} # Avoids rate limits

- name: fly-github-release
  type: github-release
  source:
    owner: concourse
    repository: fly
    access_token: {{github_access_token}} # Avoids rate limits


- name: bosh-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    access_token: {{github_access_token}} # Avoids rate limits
- name: bosh-cli-s3-release
  type: s3
  source:
    versioned_file: bosh-cli/bosh
    bucket: pcf-docker-pipeline
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: eu-west-1
