---
jobs:
- name: build-pcfops-image
  public: true
  serial: true
  plan:
  - get: pcfops-docker
    trigger: true
  - put: pcfops-image
    params: {build: pcfops-docker}

resources:
- name: pcfops-docker
  type: git
  source:
    uri: https://github.com/EngineerBetter/pcfops-docker
    branch: master

- name: pcfops-image
  type: docker-image
  source:
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-repository}}
